# Generated by Django 3.1.7 on 2021-08-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='images/equipments/')),
            ],
        ),
    ]
