# Generated by Django 3.2.6 on 2021-08-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plants_name', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='images/equipments/')),
            ],
        ),
    ]
